name: test

on:
  push:
    branches:
      - '*'

jobs:
  macos:
    strategy:
      matrix:
        kubernetes: ['v1.19.2', 'v1.18.9', 'v1.17.12', 'v1.16.15']
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the binary
      run: go build

    - name: Install Minikube
      run: brew install minikube

    - name: Start Minikube
      run: minikube start --kubernetes-version ${{ matrix.kubernetes }}

    - name: Run the binary
      run: ./minikubehostpatcher

    - name: Run the binary again
      run: ./minikubehostpatcher
